### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by ChrisTroina** [benmiller314/cdm2023spring#4]
In my audio narrative I plan to have it be about a snippet of a bland day in the life of an average college student. It consists of them walking into their apartment starting to type on their computer and whatever other assorted menial tasks. A bit into it however they hear a loud sound and are transported into a sort of distorted negative world as a mysterious voice guides them to some sort of important task.

<html><body>
<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-8b102035-7fff-98cb-4e86-6721bdb2cc1d">

Sound | Source
-- | --
Closing door | Stock sound
Fan ambience | Record myself
Generic-ish guitar music | CC
Window shattering | Stock sound
Keyboard typing | Record myself
All dialogue | Record myself
Key clattering | Record myself
Bird ambience | Stock sound
Footsteps | Stock sound

</div>
</body>
</html>

https://github.com/ChrisTroina/audio-narrative-2023spring

**Comment by benmiller314** [comment]
Thanks, Christopher! I'm curious to see what task the hero is called to perform. :¬)

And now I see you've reposted this on the other thread, so I'll close this issue. Please do let me know if I can be of more direct help, though!
